services:
  backend:
    environment:
      HTTPS: false
      SESSION_SECRET: ${SESSION_SECRET}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
